### ISSUE TITLE
README.md practical.json example misses Book 2

### ISSUE THREAD

**Issue by gustavAR** [kemayo/leech#32]
Due to some unfortunate formatting on the homepage of A Practical Guide to Evil, the example from the README.md will only download books 1, 3, 4, and 5. This can be fixed by complicating the chapter selector somewhat, though there is probably a nicer way to go about it.

#### Current practical.json
```js
{
    "url": "https://practicalguidetoevil.wordpress.com/table-of-contents/",
    "title": "A Practical Guide To Evil: Book 1",
    "author": "erraticerrata",
    "chapter_selector": "#main .entry-content > ul > li > a",
    "content_selector": "#main .entry-content",
    "filter_selector": ".sharedaddy, .wpcnt, style",
    "cover_url": "https://gitlab.com/Mikescher2/A-Practical-Guide-To-Evil-Lyx/raw/master/APGTE_1/APGTE_front.png"
}
```

#### Proposed practical.json
```js
{
    "url": "https://practicalguidetoevil.wordpress.com/table-of-contents/",
    "title": "A Practical Guide To Evil",
    "author": "erraticerrata",
    "chapter_selector": "#main .entry-content > ul > li > ul > li > a, #main .entry-content > ul > li > a",
    "content_selector": "#main .entry-content",
    "filter_selector": ".sharedaddy, .wpcnt, style",
    "cover_url": "https://gitlab.com/Mikescher2/A-Practical-Guide-To-Evil-Lyx/raw/master/APGTE_1/APGTE_front.png"
}
```

**Comment by alok** [comment]
@gustavAR Any idea how to get the extra chapters properly selected as well?

**Comment by TheMetalCenter** [comment]
> @gustavAR Any idea how to get the extra chapters properly selected as well?

Might be difficult since it is a separate table of contents. This json will grab the extra chapters only, and you can combine with the regular chapter epub in calibre or similar software relatively easily. 
`{
	"url": "https://practicalguidetoevil.wordpress.com/extra-chapters/",
	"title": "A Practical Guide To Evil: Extra Chapters",
	"author": "erraticerrata",
	"chapter_selector": "#main .entry-content > ul:nth-of-type(1) > li > a",
	"content_selector": "#main .entry-content",
	"filter_selector": ".sharedaddy, .wpcnt, style"
}
`

**Comment by kemayo** [comment]
I altered the readme in 9c9877ed26fc441cb7d50cde2ca27f71994afbba in, admittedly, the opposite direction -- I made it actually download just book 1 like it said it would.

I also took the opportunity to update the practical guide JSON in the examples folder, to show how to mix in the extras chapters when they were published.

If what you want is the entire series in one file, including all the extras, you could do this:

```
{
    "url": "https://practicalguidetoevil.wordpress.com/2015/03/25/prologue/",
    "title": "A Practical Guide To Evil",
    "author": "erraticerrata",
    "content_selector": "#main .entry-wrapper",
    "content_title_selector": "h1.entry-title",
    "content_text_selector": ".entry-content",
    "filter_selector": ".sharedaddy, .wpcnt, style",
    "next_selector": "a[rel=\"next\"]"
}
```

**Comment by TheMetalCenter** [comment]
> I altered the readme in [9c9877e](https://github.com/kemayo/leech/commit/9c9877ed26fc441cb7d50cde2ca27f71994afbba) in, admittedly, the opposite direction -- I made it actually download just book 1 like it said it would.
> 
> I also took the opportunity to update the practical guide JSON in the examples folder, to show how to mix in the extras chapters when they were published.
> 
> If what you want is the entire series in one file, including all the extras, you could do this:
> 
> ```
> {
>     "url": "https://practicalguidetoevil.wordpress.com/2015/03/25/prologue/",
>     "title": "A Practical Guide To Evil",
>     "author": "erraticerrata",
>     "content_selector": "#main .entry-wrapper",
>     "content_title_selector": "h1.entry-title",
>     "content_text_selector": ".entry-content",
>     "filter_selector": ".sharedaddy, .wpcnt, style",
>     "next_selector": "a[rel=\"next\"]"
> }
> ```

Thanks for this! This JSON did give an error for me. Removing   `    "content_title_selector": "h1.entry-title",`  allowed it to run successfully, but doesn't grab chapter names (unsuprising since that is what it is meant to do). I will mess with it later and see if I can figure out solution. 

error:
`C:\Users\conno\Downloads\Recent\leech-master>py -3.7 leech.py practicals.json
[sites] Handler: <class 'sites.arbitrary.Arbitrary'> (practicals.json)
[__main__] Unable to locate leech.json. Continuing assuming it does not exist.
[sites.arbitrary] Extracting chapter @ https://practicalguidetoevil.wordpress.com/2015/03/25/prologue/
Traceback (most recent call last):
  File "leech.py", line 157, in <module>
    cli()
  File "C:\Users\conno\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\conno\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "leech.py", line 150, in download
    story = open_story(site, url, session, login, options)
  File "leech.py", line 101, in open_story
    story = handler.extract(url)
  File "C:\Users\conno\Downloads\Recent\leech-master\sites\arbitrary.py", line 80, in extract
    for chapter in self._chapter(content_url, definition):
  File "C:\Users\conno\Downloads\Recent\leech-master\sites\arbitrary.py", line 115, in _chapter
    title = title[0].string
TypeError: 'bool' object is not subscriptable`

**Comment by kemayo** [comment]
> Thanks for this! This JSON did give an error for me. Removing "content_title_selector": "h1.entry-title", allowed it to run successfully, but doesn't grab chapter names (unsuprising since that is what it is meant to do). I will mess with it later and see if I can figure out solution.

In this case, I'm pretty sure it's just that you have an outdated checkout. 532a7c6682467e25d1e57c4182d6ae2e9c28cfc6 from mid-2019 fixed an error on that line so it's no longer `title = title[0].string`.

**Comment by TheMetalCenter** [comment]
> > Thanks for this! This JSON did give an error for me. Removing "content_title_selector": "h1.entry-title", allowed it to run successfully, but doesn't grab chapter names (unsuprising since that is what it is meant to do). I will mess with it later and see if I can figure out solution.
> 
> In this case, I'm pretty sure it's just that you have an outdated checkout. [532a7c6](https://github.com/kemayo/leech/commit/532a7c6682467e25d1e57c4182d6ae2e9c28cfc6) from mid-2019 fixed an error on that line so it's no longer `title = title[0].string`.

Oops yeah, that is probably the issue. I forgot that I have been using an older version because I couldn't get some of the newer updates to work due to some not finding the PIL module issues, even though py says pillow is installed. I think it is caused by issues on my end from having too many versions of python installed. 

Thanks for the help!

EDIT: Oh that was an easy fix, I went into cover.py and changed "PIL" in the first line to "pil" and it started working.

**Comment by TheMetalCenter** [comment]
> I altered the readme in [9c9877e](https://github.com/kemayo/leech/commit/9c9877ed26fc441cb7d50cde2ca27f71994afbba) in, admittedly, the opposite direction -- I made it actually download just book 1 like it said it would.
> 
> I also took the opportunity to update the practical guide JSON in the examples folder, to show how to mix in the extras chapters when they were published.

So sorry to keep bothering you! After updating and solving the pillow thing above and getting the full book json you posted to work successfylly, I went and tried the new practical examples for single book jsons and have run into an issue.

`  File "C:\leech-master\sites\arbitrary.py", line 85, in extract
    next_link = soup.select(definition.next_selector)
  File "C:\Python38\lib\site-packages\bs4\element.py", line 1527, in select
    raise NotImplementedError(
NotImplementedError: Only the following pseudo-classes are implemented: nth-of-type.`

I get this NotImplementedError, which seems centered around the "not" modifier on this line
`    "next_selector": "a[rel=\"next\"]:not([href*=\"prologue\"])",`

I played around with it for a couple of hours to find a solution but was unsuccessful. If relevant, this is python38 and beautifulsoup 4.9.3. 

Thanks for all the help/development, and I've been enjoying tinkering with the package almost as much as reading the books it produces!

**Comment by kemayo** [comment]
This is because of an outdated BeautifulSoup dependency -- versions before 4.7.0 had a much less complete selector implementation. Update BeautifulSoup and it should all be good.

**Comment by TheMetalCenter** [comment]
Hmm yeah, that was my thought but it said it was up to date at 4.9.3. Maybe I’ll try a clean install.

**Comment by kemayo** [comment]
BeautifulSoup has a dependency on a package called soupsieve that actually handles the selectors, so it's possible it's just that which is outdated.

**Comment by TheMetalCenter** [comment]
> BeautifulSoup has a dependency on a package called soupsieve that actually handles the selectors, so it's possible it's just that which is outdated.

Got it working! Used a clean python3.9 and it was working as expected, so then went back to the python3.8 to try and troubleshoot why it wasn't working there. Apparently, I had "bs4" installed as bs4 version 4.6.3 but also had "beautifulsoup4" installed as beautifulsoup4 4.9.3. It said bs4 was fully up to date, so I just uninstalled it and it started working, I guess defaulting to beautifulsoup4.

Thanks for the help!
